### ISSUE TITLE
Upload seemingly fails because of API change

### ISSUE THREAD

**Issue by tfohlmeister** [konsorten/sevdesk-voucher-upload#2]
Sevdesk API has changed and now returns a sub property `voucher` for rest call `saveVoucher` (check [their swagger](https://my.sevdesk.de/swaggerUI/index.html#/Voucher/saveVoucher))

So while the voucher upload still works, this library now returns an error which is not correct. I fixed it in MR #1, please check.

**Comment by fkollmann** [comment]
Hi Thorben, thanks for the PR! I am already working on testing it. I will try to finish testing this week. Best Regards, Felix

**Comment by tfohlmeister** [comment]
Hi Felix,

its been a month, any progress on this?

**Comment by fkollmann** [comment]
Hi, I am unable to reproduce the issues.... I guess Sevdesk fixed this on their side? Can you re-check on your side, please? Best Regards, Felix

```json
{
    "voucher": {
        "id": "13786300",
        "objectName": "Voucher",
        "additionalInformation": null,
        "create": "2020-05-12T21:48:04+02:00",
        "update": "2020-05-12T21:48:04+02:00",
        "sevClient": {
            "id": "47880",
            "objectName": "SevClient"
        },
        "createUser": {
            "id": "198734",
            "objectName": "SevUser"
        },
        "voucherDate": "2020-05-12T00:00:00+02:00",
        "supplierName": "???",
        "description": null,
        "document": {
            "id": "23315857",
            "objectName": "Document"
        },
        "payDate": null,
        "status": "50",
        "sumNet": "0",
        "sumTax": "0",
        "sumGross": "0",
        "sumNetAccounting": "0",
        "sumTaxAccounting": "0",
        "sumGrossAccounting": "0",
        "showNet": "0",
        "paidAmount": "0",
        "taxType": "default",
        "creditDebit": "C",
        "hidden": "0",
        "voucherType": "VOU",
        "recurringIntervall": null,
        "recurringStartDate": null,
        "recurringNextVoucher": null,
        "recurringLastVoucher": null,
        "recurringEndDate": null,
        "enshrined": null,
        "inSource": null,
        "iban": null,
        "accountingSpecialCase": null,
        "paymentDeadline": null,
        "tip": "0",
        "mileageRate": "0",
        "selectedForPaymentFile": "0",
        "supplierNameAtSave": "",
        "taxmaroStockAccount": null,
        "vatNumber": null,
        "sumNetForeignCurrency": "0",
        "sumTaxForeignCurrency": "0",
        "sumGrossForeignCurrency": "0"
    },
    "voucherPos": [/*removed*/],
    "document": {
        "id": "23315857",
        "objectName": "Document",
        "additionalInformation": null,
        "create": "2020-05-12T21:48:04+02:00",
        "update": "2020-05-12T21:48:04+02:00",
        "documentNumber": null,
        "createUser": {
            "id": "198734",
            "objectName": "SevUser"
        },
        "updateUser": {
            "id": "198734",
            "objectName": "SevUser"
        },
        "mimeType": null,
        "description": null,
        "sevClient": {
            "id": "47880",
            "objectName": "SevClient"
        },
        "filename": "7a34daf79179b5016d808341d36642e4",
        "status": "50",
        "extension": "pdf",
        "filesize": "80238"
    }
}
```

**Comment by tfohlmeister** [comment]
You are right - seems they added back the `document` property. Maybe because it was breaking some clients.
However as far as I can tell from their swagger this is not what the result should look like. So in my opinion the documentId is now to be found in `voucher.document.id`.

Anyway its up to you now Felix - as this package is no longer broken you can close this issue and my MR or merge it and have the client behave "on-spec", which might or might not be more future proof.

**Comment by tfohlmeister** [comment]
Just a quick follow up:
sevDesk got in contact with me because the result of their automatic content recognition of my vouchers looked weird to them. Also this feature for me wasn't working anymore for a couple of weeks now. I told them I was using this tool and they suggested to use newer endpoints and a simpler approach.
I quickly threw together a python script which basically does the same as this project using a single POST request to `createVoucherFromFile`: https://github.com/tfohlmeister/sevdesk-voucher-uploader
